FROM eclipse-temurin:25-jdk AS build

WORKDIR /app

COPY . .

RUN sed -i 's/\r//' gradlew
RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon
RUN ./gradlew bootJar --no-daemon

FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 6001

ENTRYPOINT ["java", "-jar", "app.jar"]