server:
  port: 6001

spring:
  application:
    name: fairticket
  datasource:
    url: jdbc:postgresql://localhost:5432/fairticket
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
app:
  security:
    secret: ${JWT_SECRET:mi-clave-secreta-super-larga-de-al-menos-256-bits-para-hmac-sha}
    expiration: ${JWT_EXPIRATION:86400000}